import type { Metadata } from "next";
import localFont from "next/font/local";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
// import Font from "../../public/fonts/technology/Technology-Bold.woff2";

const spaceGrotesk = Space_Grotesk({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  weight: ["300", "400", "500",  "600", "700"],
});

const technology = localFont({
  src: [
    {
      path: "../../public/fonts/technology/Technology-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/technology/Technology.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-technology",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" type="image/svg+xml" href=""></link> */}
        <title>Kushnir Web Dev</title>
      </head>
      <body className={`${spaceGrotesk.className} ${spaceGrotesk.variable} ${technology.className} ${technology.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
